name: Update profile metrics

on:
  schedule:
    - cron: "17 6 * * *"   # daily
  workflow_dispatch:

# allows the built-in GITHUB_TOKEN to commit files
permissions:
  contents: write

jobs:
  metrics_summary:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}        # PAT with read:user + repo
          user: robertguarneros
          template: classic
          base: header, activity, community, repositories
          plugin_streak: yes
          plugin_streak_days: 7,30
          config_timezone: Europe/Madrid
          filename: metrics.svg
          output_action: commit
          committer_branch: main
          committer_message: "chore: update metrics.svg"

  metrics_languages:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}        # same PAT
          user: robertguarneros
          template: classic
          base: ""
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 10
          plugin_languages_details: percentage
          plugin_languages_threshold: 0%
          config_timezone: Europe/Madrid
          filename: languages.svg
          output_action: commit
          committer_branch: main
          committer_message: "chore: update languages.svg"

  contrib_3d:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # This action expects ENV vars; use github.token (not secrets)
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ github.token }}          # <-- fix for "GITHUB_TOKEN is empty"
          USERNAME: robertguarneros

      - name: Select theme
        run: cp -f profile-3d-contrib/profile-night-rainbow.svg contrib-3d.svg

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update contrib-3d.svg"
          file_pattern: contrib-3d.svg
